name: Sync Fork

on:
  schedule:
    - cron: '0 0 16 * *' # every 16th of each month
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission to the workflow

    steps:
      - name: Checkout your forked repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: fetch upstream changes remote
        run: |
          git remote add upstream https://github.com/getsentry/self-hosted.git
          git fetch upstream

      - name: Merge upstream into your branch
        run: |
          git checkout master
          git rebase upstream/master

      - name: Push updates to your GitHub fork
        run: git push origin master --force
