name: Sync Fork

on:
  schedule:
    - cron: '0 0 16 * *' # every 16th of each month
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission to the workflow

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: fetch upstream changes remote
        run: |
          git remote add upstream https://github.com/getsentry/self-hosted.git
          git fetch upstream

      - name: Merge upstream into your branch
        run: |
          git checkout master
          git rebase upstream/master

      - name: Push updates to fork
        env:
          PAT: ${{ secrets.K09_PAT }}
        run: |
          git remote set-url origin https://github-actions:${PAT}@github.com/${GITHUB_REPOSITORY}.git
          git push origin master --follow-tags
